syntax on
set nocompatible
set redrawtime=10000
set background=dark
set laststatus=2
set noerrorbells
set expandtab
set smartindent
set nu
set nowrap
set nobackup
set undodir=~/.vim/undordir
set undofile 
set incsearch
set cursorline
set termguicolors
